Web 746
thegoodparty/gp-webapp pull request #27
Opened 2023-06-02 22:08 UTC by taylorgp

2023-06-03 19:27 UTC, tomer-tgp requested changes

2023-06-03 19:27 UTC, tomer-tgp commented on app/(company)/run-for-office/components/Features.js
> +          </div>
you should use a grid here

2023-06-03 19:27 UTC, tomer-tgp commented on app/(company)/run-for-office/components/Features.js
> +          <div className="flex flex-col justify-center flex-auto md:w-1/3">
use a grid here too

2023-06-03 19:27 UTC, tomer-tgp commented on app/(company)/run-for-office/components/Features.js
> +                  children={features[index].description}
why not add the icon and bg to the array and just iterate over it?

2023-06-03 19:27 UTC, tomer-tgp commented on app/(company)/run-for-office/components/Features.js
> +                <div className="tracking-wide">GET A DEMO</div>
grid

2023-06-03 19:27 UTC, tomer-tgp commented on app/(company)/run-for-office/components/HeroImages.js
> +        sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
nice!

2023-06-06 16:01 UTC, tomer-tgp approved these changes

2023-06-08 14:51 UTC, tomer-tgp requested changes
one more small change

2023-06-08 14:51 UTC, tomer-tgp commented on app/(company)/run-for-office/components/Blog.js
> +        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
please keep the grid the same way I use it everywhere:
use `grid grid-cols-12` at the container
and in the children use
`col-span-12 lg:col-span-4`

2023-06-08 14:51 UTC, tomer-tgp commented on app/(company)/run-for-office/components/Hero.js
> +        <div className="col-span-12 md:col-span-6">
This is the way
https://i.kym-cdn.com/photos/images/newsfeed/001/653/546/4b2.jpg

2023-06-09 22:04 UTC, taylorgp commented
please merge whenever you're ready.

2023-06-10 04:25 UTC, tomer-tgp approved these changes

2023-06-10 04:25 UTC, merged