feat: new loading and regenerating state.
thegoodparty/gp-webapp pull request #72
Opened 2023-08-28 18:02 UTC by taylorgp

2023-08-28 20:27 UTC, tomer-tgp requested changes
Small comment. besides that looks good

2023-08-28 20:27 UTC, tomer-tgp commented on app/(candidate)/dashboard/content/[slug]/components/ContentEditor.js
> -import LoadingAI from 'app/(candidate)/onboarding/[slug]/campaign-plan/components/LoadingAI';
if this is not used, let's delete the file

2023-08-28 23:10 UTC, taylorgp commented
I believe it is still used by the onboarding ai content.

On Mon, Aug 28, 2023 at 1:28 PM tomer-tgp ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Small comment. besides that looks good
> ------------------------------
>
> In app/(candidate)/dashboard/content/[slug]/components/ContentEditor.js
> <https://github.com/thegoodparty/gp-webapp/pull/72#discussion_r1307918495>
> :
>
> > @@ -6,7 +6,7 @@ import { globalSnackbarState } from ***@***.***/utils/Snackbar';
>  import { updateCampaign } from 'app/(candidate)/onboarding/shared/ajaxActions';
>  import PlanVersion from './PlanVersion';
>  import PrimaryButton from ***@***.***/buttons/PrimaryButton';
> -import LoadingAI from 'app/(candidate)/onboarding/[slug]/campaign-plan/components/LoadingAI';
>
> if this is not used, let's delete the file
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/thegoodparty/gp-webapp/pull/72#pullrequestreview-1599060853>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5YJRWDEEVNB444MVR4Z6HTXXT5NDANCNFSM6AAAAAA4BYWQY4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-29 19:55 UTC, taylorgp commented
this should be good to merge

2023-08-30 16:14 UTC, tomer-tgp approved these changes

2023-08-30 16:14 UTC, merged