feat: WEB-168 remove hero
thegoodparty/gp-webapp pull request #9
Opened 2023-02-16 17:35 UTC by taylorgp

2023-02-27 16:46 UTC, tomer-tgp requested changes

2023-02-27 16:46 UTC, tomer-tgp commented on app/faqs/components/FaqsPage.js
> +      {/* <Hero /> */}
let's delete the line instead of commenting it out.

2023-02-27 16:46 UTC, tomer-tgp commented on app/faqs/components/FaqsPage.js
> +      {/* <Hero /> */}
Also remove the import from line 4 and delete the Hero file please

2023-03-01 23:18 UTC, talmog approved these changes

2023-03-01 23:32 UTC, merged